ingress:
  hosts:
    - host: pbotapps.portland.gov
      paths:
        - path: /streets-pdx
          pathType: Prefix
  tls:
    - secretName: pbotapps-portland-gov-tls
      hosts:
        - pbotapps.portland.gov
